# Add this file to .gitignore right now !!!
default: &default
  basecampbot_url: https://3.basecamp.com/3700178/integrations/3gtJyBKVQHvrQN2h7FitRJSK/buckets/3097353/chats/437772399/lines
  snstopic_arn: arn:aws:sns:us-west-2:230306836787:magick_kick
  # Path to the .yml file that contains 'aws_access_key' and 'aws_secret_key'
  aws_secret_file: /home/klim/aws.yml
  # Giphy public API key
  giphy_api_key: "dc6zaTOxFJmzC"

development:
  <<: *default

test:
  <<: *default

production:
  basecampbot_url: <%= ENV["BASECAMPBOT_URL"] %>
  giphy_api_key: <%= ENV["GIPHY_API_KEY"] %>
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_KEY_ID"] %>
